projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('dashboard', views.dashboard, name="dashboard"),
    path('create', views.create_project, name="create_project"),
    path('update/<int:prj_id>', views.update_project, name="update_project"),
    path('<int:prj_id>', views.project_page, name="project"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register, name="register"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('manage', views.manage_view, name="manage"),
]

wordsalad/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('projects/', include('projects.urls')),
    path('users/', include('users.urls'))
]

projects/models.py
from django.db import models
from users.models import User

# Create your models here.
class Type(models.Model):
  name = models.CharField(max_length=100, blank=False)

  def __str__(self):
    return self.name

class Genre(models.Model):
  name = models.CharField(max_length=100, blank=False)

  def __str__(self):
    return self.name

class Project(models.Model):
  name = models.CharField(max_length=100, blank=False)
  summary = models.TextField(blank=True)
  insertion_date = models.DateTimeField(auto_now_add=True)
  target_count = models.IntegerField(blank=False)
  user_id = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
  type_id = models.ForeignKey(Type, on_delete=models.SET(1), default=None, verbose_name="Type")
  genres = models.ManyToManyField(
    Genre,
    db_table="project_genre"
  )

  def __str__(self):
    return self.name

class Progress(models.Model):
  word_count = models.IntegerField(blank=False)
  insertion_date = models.DateTimeField(auto_now_add=True)
  user_id = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
  project_id = models.ForeignKey(Project, on_delete=models.CASCADE, default=None, verbose_name="Project")

  def __str__(self):
    return self.project_id.__str__() + self.word_count.__str__()

projects/forms.py
from django import forms
from . import models

class CreateProjects(forms.ModelForm):
  class Meta:
    model = models.Project
    fields = ['name', 'summary', 'target_count', 'genres', 'type_id']

class LogProgressProject(forms.ModelForm):
  class Meta:
    model = models.Progress
    fields = ['word_count']

class LogProgressDashboard(forms.ModelForm):
  class Meta:
    model = models.Progress
    fields = ['word_count', 'project_id']

projects/views.py
from django.shortcuts import render, redirect
from .models import Project, Progress, Genre, Type
from users.models import User
from django.contrib.auth.decorators import login_required
from django.utils.timezone import activate, localtime
from . import forms
from .utils.get_progress_color import get_progress_color
from .utils.format_donut_chart_data import format_donut_chart_data
from .utils.format_line_chart_data import format_line_chart_data

# Create your views here.
@login_required(login_url="/users/login")
def dashboard(request):
  projects = Project.objects.filter(user_id=request.user).order_by('-insertion_date')
  user = User.objects.get(id=request.user.id)
  activate(user.timezone)

  most_recent_progress = Progress.objects.filter(user_id=request.user).order_by('-insertion_date').first()
  most_recent_progress.color = get_progress_color((most_recent_progress.word_count / most_recent_progress.project_id.target_count) * 100)

  most_advanced_project = Progress.objects.filter(user_id=request.user).order_by('-word_count').first()
  most_advanced_project.color = get_progress_color((most_advanced_project.word_count / most_advanced_project.project_id.target_count) * 100)

  for project in projects:
    project.percentage = 0
    project.word_count = 0
    last_progress = Progress.objects.filter(project_id=project.id, user_id=request.user).order_by('-insertion_date').first()
    if last_progress is not None:
      project.percentage = round((last_progress.word_count / project.target_count) * 100, 1)
      project.word_count = last_progress.word_count
    project.color = get_progress_color(project.percentage)

  if request.method == "POST":
    form = forms.LogProgressDashboard(request.POST)

    if form.is_valid():
      # save with user
      new_progress = form.save(commit=False)
      new_progress.user_id = request.user
      new_progress.save()

      return redirect('projects:dashboard')

  else:
    form = forms.LogProgressDashboard()

  chart_data = format_donut_chart_data(projects)
  # print(chart_data)

  return render(request, 'projects/dashboard.html', {
    'projects': projects,
    'form': form,
    'chart_data': chart_data,
    'most_recent_progress': most_recent_progress,
    'most_advanced_project': most_advanced_project
  })

@login_required(login_url="/users/login")
def project_page(request, prj_id):
  # Using that instead of .get() to avoid getting an error if project doesn't exist
  # print(prj_id)
  user = User.objects.get(id=request.user.id)
  activate(user.timezone)

  project = Project.objects.filter(id=prj_id).first()
  genres = project.genres.all()
  progress = Progress.objects.filter(project_id=prj_id, user_id=request.user).order_by('-insertion_date')
  most_recent_count = progress.first()

  if project is None:
    return redirect('projects:dashboard')

  if project.user_id != request.user:
    return redirect('projects:dashboard')

  if most_recent_count is None:
    percentage = 0

  else:
    percentage = round((most_recent_count.word_count / project.target_count) * 100, 1)

  if request.method == "POST":
    form = forms.LogProgressProject(request.POST)

    if form.is_valid():
      # save with user
      new_progress = form.save(commit=False)
      new_progress.user_id = request.user
      new_progress.project_id = project
      new_progress.save()

      return redirect('projects:project', prj_id=project.id)

  else:
    form = forms.LogProgressProject()

  project.insertion_date = localtime(project.insertion_date).strftime("%d/%m/%Y %H:%M")
  for entry in progress:
    entry.insertion_date = localtime(entry.insertion_date).strftime("%d/%m/%Y %H:%M")

  datapoints = format_line_chart_data(progress.reverse(), project.target_count)

  # print(project.__dict__)
  return render(request, 'projects/project_page.html', {
    'project': project,
    'genres': genres,
    'progress': progress,
    'most_recent_count':most_recent_count,
    'percentage': percentage,
    'color': get_progress_color(percentage),
    'form': form,
    'datapoints': datapoints
  })

@login_required(login_url="/users/login")
def create_project(request):
  if request.method == "POST":
    form = forms.CreateProjects(request.POST)

    if form.is_valid():
      # save with user
      new_post = form.save(commit=False)
      new_post.user_id = request.user
      new_post.save()

      for genre in request.POST["genres"]:
        new_post.genres.add(genre)
        new_post.save()

      return redirect('projects:dashboard')

  else:
    form = forms.CreateProjects()

  return render(request, 'projects/create_project.html', {
    'form': form
  })

@login_required(login_url="/users/login")
def update_project(request, prj_id):
  project = Project.objects.filter(id=prj_id).first()
  # genres = project.genres.all()
  # print("update")
  # project.genres = genres
  id = project.id

  if request.method == "POST":
    form = forms.CreateProjects(request.POST)
    # print(form)
    if form.is_valid():
      # save with user
      # print(form["target_count"].value())
      project.name = form["name"].value()
      project.summary = form["summary"].value()
      project.target_count = form["target_count"].value()
      new_type = Type.objects.get(id=form["type_id"].value())
      project.type_id = new_type
      project.save()

      project.genres.clear()
      print(request.POST["genres"])
      print("length")
      print(len(request.POST["genres"]))
      for genre in request.POST["genres"]:
        # print(genre)
        new_genre = Genre.objects.get(id=genre)
        project.genres.add(new_genre)

      project.save()

      return redirect('projects:project', prj_id=id)

  else:
    form = forms.CreateProjects(instance=project)

  return render(request, 'projects/update_project.html', {
    'form': form,
    'project_id': id,
  })

projects/templates/projects/create_project.html
{% extends 'layout.html' %}

{% block title %} Create a project {% endblock %}

{% block content %}
    <section>
        <h1>Create a project</h1>
        <form method="post" class="form-w-validation" action="{% url 'projects:create_project' %}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="primary-btn">Create</button>
        </form>
    </section>

{% endblock %}

projects/templates/projects/dashboard.html
{% extends 'layout.html' %}

{% block title %} WordSalad | Dashboard {% endblock %}

{% block script %}
    <script>
        window.addEventListener("load", (event) => {
            const chart = new CanvasJS.Chart("chartContainer",{
                theme: "dark2",
                animationEnabled: false,
                exportEnabled: false,
                backgroundColor: 'transparent',
                height: 395,
                data: [{
                    type: "doughnut",
                    indexLabel: "{y}",
                    indexLabelPlacement: 'inside',
                    indexLabelFontColor: "hsl(220, 12%, 7%)",
                    indexLabelFontSize: 24,
                    indexLabelFontWeight: 700,
                    explodeOnClick: false,
                    yValueFormatString: "#,##",
                    startAngle: 90,
                    highlightEnabled: false,
                    dataPoints: {{ chart_data|safe }}
                }],
                toolTip: {
                    enabled: false,
                },
            });
            chart.render();
        });
    </script>
{% endblock %}

{% block content %}
    <div class="dashboard-ctn">
        <section class="donut-chart">
            <div id="chartContainer" style="width: 100%; height: 360px;"></div>
        </section>
        <section class="progress-form-dbd">
            <h2>Log your progress</h2>
            <form action="/projects/dashboard" method="post" class="form-w-validation-hr">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="primary-btn">Submit</button>
            </form>
        </section>
        <section class="statistics">
            <div class="stats-ctn">
            <div>
                <h2>Your most recent progress log</h2>
                <p>
                    <span class="statistics-emphasis">
                        {{ most_recent_progress.project_id.name }}
                    </span> with <span class="statistics-emphasis" style="color: {{ most_recent_progress.color }};">
                        {{ most_recent_progress.word_count }}
                    </span> words
                </p>
            </div>
            <div>
                <h2>Your biggest project</h2>
                <p>
                    <span class="statistics-emphasis">
                        {{ most_advanced_project.project_id.name }}
                    </span> with <span class="statistics-emphasis" style="color: {{ most_advanced_project.color }};">
                        {{ most_advanced_project.word_count }}
                    </span> words
                </p>
            </div>
        </div>
        <p class="encouragments">Congratulations on your hard work!</p>
        </section>
        <section class="projects-list">
            <div class="title-ctn">
                <h2>Projects</h2>
                <a href="{% url 'projects:create_project' %}" class="link-btn primary-btn">Create project</a>
            </div>
            <ul class="projects-ctn">
                {% for project in projects %}
                    <li class="project-item">
                        <h3>
                            <a href="{% url 'projects:project' prj_id=project.id %}">{{ project.name }}</a>
                        </h3>
                        <p>{{project.word_count}}/{{project.target_count}} words</p>
                        <div class="bar-ctn" title="{{ project.percentage}}%">
                            <div
                                class="bar"
                                style="width:{{ project.percentage }}%;max-width: 100%;background-color: {{ project.color }};"
                            />
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </section>
    </div>
{% endblock %}

projects/templates/projects/project_page.html
{% extends 'layout.html' %}

{% block title %} {{ project.name }} {% endblock %}

{% block script %}
    <script>
        window.onload = function () {

            const chart = new CanvasJS.Chart("chartContainer", {
                theme: "dark2",
                exportEnabled: false,
                animationEnabled: false,
                backgroundColor: 'transparent',
                height: 345,
                title: {
                    text: "Progress"
                },
                axisY: {
                    title: "Words typed",
                    minimum: 0,
                    maximum: Math.max({{ project.target_count }}, {{ most_recent_count.word_count }}),
                    gridColor: "hsl(220, 12%, 20%)",
                    tickColor: "hsl(220, 12%, 20%)",
                },
                data: [{
                    type: "line",
                    dataPoints: {{ datapoints|safe }}
                }]
            });

            chart.render();
        }
    </script>
{% endblock %}

{% block content %}

    <h1>{{ project.name }}</h1>
    <div class="project-ctn">
        <section class="project-progress-bar">
            <div class="bar-ctn">
                <div class="bar" style="width:{{ percentage }}%;max-width: 100%;background-color: {{ color }};"></div>
            </div>
                <p class="percentage" style="color: {{ color }};">{{ percentage }}%</p>
            <p class="word-count">
                {% if  most_recent_count is None%}
                    <strong style="color: {{ color }};">0</strong>
                {% else %}
                    <strong style="color: {{ color }};">{{ most_recent_count.word_count }}</strong>
                {% endif %}
                of <strong>{{ project.target_count }}</strong> words written
            </p>
        </section>
        <section class="progress-form-prj">
            <h2>Log your progress</h2>
            <form action="/projects/{{ project.id }}" method="post" class="form-w-validation-hr">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="primary-btn">Submit</button>
            </form>
        </section>
        <section class="project-summary">
            <p>{{ project.insertion_date }}</p>
            <p>{{ project.type_id}}</p>
            <p>{% for genre in genres %} <span>{{ genre }}</span> {% endfor %}</p>
            <p>{{ project.summary }}</p>
            <a href="{% url 'projects:update_project' prj_id=project.id %}" class="link-btn primary-btn">Update</a>
        </section>
        <section class="progress-chart">
            <div id="chartContainer" style="height: 360px; width: 100%;"></div>
        </section>
        <section class="project-log">
            <h2>Progress Log</h2>
            <ul>
                {% for item in progress %}
                    <li class="project-item">
                        {{ item.insertion_date }}
                        {{ item.word_count }} words
                    </li>
                {% endfor %}
            </ul>
        </section>
    </div>

{% endblock %}

projects/templates/projects/update_project.html
{% extends 'layout.html' %}

{% block title %} Update a project {% endblock %}

{% block content %}
    <section>
        <h1>Update a project</h1>
        <form method="post" class="form-w-validation" action="{% url 'projects:update_project' prj_id=project_id %}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="primary-btn">Update</button>
        </form>
    </section>

{% endblock %}