projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('dashboard', views.dashboard, name="dashboard"),
    path('create', views.create_project, name="create_project"),
    path('update/<int:prj_id>', views.update_project, name="update_project"),
    path('<int:prj_id>', views.project_page, name="project"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register, name="register"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('manage', views.manage_view, name="manage"),
]

wordsalad/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('projects/', include('projects.urls')),
    path('users/', include('users.urls'))
]

templates/home.html
{% extends 'layout_unlogged.html' %}

{% block title_unlogged %}Word Salad | Home{% endblock %}

{% block body %}
    <div class="home">
        <h1>Welcome to <span class="emphasis">Word Salad</span></h1>
        <p>Keep track of your writing projects and the words you've written for them!</p>
        <div class="btn-ctn">
            <a href="{% url 'users:register' %}" class="link-btn  primary-btn">Register</a>
            <a href="{% url 'users:login' %}" class="link-btn  primary-btn">Login</a>
        </div>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/ca9ca94b48.js" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
    <title>
        {% block title %}
            Word Salad
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/canvasjs.min.js' %}"></script>
</head>
<body>
    <aside>
        <header>
            <p><i class="fa-solid fa-spa"></i></p>
        </header>
        <nav>
            <a href="{% url 'projects:dashboard' %}" alt="Dashboard" title="Dashboard"><i class="fa-solid fa-table-columns"></i></a>
            <a href="{% url 'projects:create_project' %}" alt="create project" title="Create project"><i class="fa-solid fa-square-plus"></i></a>
        </nav>
        <nav>
            <a href="{% url 'users:manage' %}" alt="Manage user" title="Manage user"><i class="fa-regular fa-circle-user"></i></i></a>
        </nav>
        <form class="logout" action="{% url 'users:logout' %}" method="POST">
            {% csrf_token %}
            <button class="logout-btn" alt="logout" title="Logout"><i class="fa-solid fa-arrow-right-from-bracket"></i></button>
        </form>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/layout_unlogged.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/ca9ca94b48.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}" defer></script>
    <title>
        {% block title_unlogged %}
            Word Salad
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <main>
        {% block body %}
        {% endblock %}
    </main>
</body>
</html>